### PR TITLE
[CMS-800] Fix uploads

### PR DESCRIPTION
**Pull request by jspellman814**
Adds configuration to pantheon.upstream.yml to resolve errors when trying to upload files to sites using this upstream.

### CODE REVIEW

**Comment by CdrMarks** [comment]
@jspellman814 is there a Jira ticket for this?  If so, can it be added in the PR subject?

**Comment by jspellman814** [comment]
@CdrMarks I just created CMS-800. This came up in Slack [this morning](https://pantheon.slack.com/archives/C024NA0Q1TJ/p1657897073498239?thread_ts=1657833428.600879&cid=C024NA0Q1TJ).

**Review by CdrMarks — APPROVED** [review]

**Review by namespacebrian — APPROVED** [review]

**Review by greg-1-anderson — CHANGES_REQUESTED** [review]
This file should be named pantheon.upstream.yml

**Review by greg-1-anderson — CHANGES_REQUESTED** [review]
Still needs:
```
# See https://pantheon.io/docs/pantheon-yml/#enforce-https--hsts for valid values.
enforce_https: transitional
```
and
```
database:
  version: 10.4
```

**Review by greg-1-anderson — APPROVED** [review]

**Pull request merged**
